/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.util.ArrayList;

/**
 *
 * @author Daniel
 */
public class StartMenu extends javax.swing.JFrame {

    static Team[] teams;
    /**
     * Creates new form StartManu
     */
    public StartMenu() {
        initComponents();
        setResizable(false);
        initTeams();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        button_start = new javax.swing.JButton();
        field_ip = new javax.swing.JTextField();
        button_connect = new javax.swing.JButton();
        field_no_connection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Football Manager Lite v 1.0");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create game");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("or");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Join existing one");

        button_start.setText("Start Game!");
        button_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_startActionPerformed(evt);
            }
        });

        button_connect.setText("Connect!");
        button_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_connectActionPerformed(evt);
            }
        });

        field_no_connection.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        field_no_connection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        field_no_connection.setText("Cannot connect to game!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button_start, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(field_ip)
                            .addComponent(button_connect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(field_no_connection, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(field_no_connection, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_start, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void initTeams(){
        Position GK = new Position("GK","C","D");
        Position CB = new Position("B","C","D");
        Position RB = new Position("B","R","D");
        Position LB = new Position("B","L","D");
        Position CM = new Position("M","C","E");
        Position CDM = new Position("M","C","D");
        Position CAM = new Position("M","C","O");
        Position ST = new Position("A","C","O");
        Position RW = new Position("A","R","O");
        Position LW = new Position("A","L","O");
        Position LWB = new Position("B","L","E");
        Position RWB = new Position("B","R","E");
        Position RM = new Position("M","R","E");
        Position LM = new Position("M","L","E");


        ArrayList <Formation> formations= new ArrayList<>();
        formations.add(new Formation("4-4-2",GK,LB,CB,CB,RB,LM,CM,CM,RM,ST,ST));
        formations.add(new Formation("4-3-3",GK,LB,CB,CB,RB,LM,CAM,RM,LW,RW,ST));
        formations.add(new Formation("4-2-3-1",GK,LB,CB,CB,RB,CM,CM,RM,LM,CAM,ST));
        formations.add(new Formation("4-3-2-1",GK,LB,CB,CB,RB,CM,CM,CM,RW,LW,ST));
        formations.add(new Formation("4-5-1",GK,LB,CB,CB,RB,LM,CM,CM,RM,CM,ST));
        formations.add(new Formation("3-4-3",GK,CB,CB,CB,CM,LM,CM,RW,RM,LW,ST));
        formations.add(new Formation("3-5-2",GK,CB,CB,CB,RM,CM,CM,CAM,LM,ST,ST));
        formations.add(new Formation("5-4-1",GK,LB,CB,CB,CB,RB,CM,CM,RM,LM,ST));
        formations.add(new Formation("5-3-2",GK,LB,CB,CB,CB,RB,CM,CM,CM,ST,ST));
        formations.add(new Formation("5-2-2-1",GK,LWB,CB,CB,RWB,CB,CM,CM,RW,LW,ST));



        // tworzenie zawodników
        Player zero= new Player ("","",GK,0,0);
        Player KNavas=new Player("Keylor", "Navas", GK ,1, 84);
        Player Marcelo=new Player("Marcelo", " ", LB, 3, 84);
        Player SRamos=new Player("Sergio", "Ramos", CB, 4, 89);
        Player Pepe=new Player("Pepe", " ", CB, 5, 84);
        Player DCarvajal=new Player("Dani", "Carvajal", RB, 63, 83);
        Player TKroos=new Player("Toni", "Kroos", CM,6, 86);
        Player LModric=new Player("Luca", "Modric", CM,18, 90);
        Player JRodriguez=new Player("James", "Rodriguez", CAM, 10, 84);
        Player CRonaldo=new Player("Cristiano", "Ronaldo", ST, 7, 96);
        Player GBale=new Player("Gareth", "Bale", RW,11, 92);
        Player AMorata=new Player("Alvaro", "Morata", ST, 19, 85);
        Player KBenzema = new Player("Karim","Benzema",ST,9,87);
        Player Isco = new Player("Isco","",CAM,22,86);
        Player Casemiro = new Player("Casemiro","",CM,21,82);
        Player MAsensio= new Player("Marco","Asensio",CAM,20,83);
        Player LVasquez= new Player("Lucas","Vasquez",LW,18,82);
        Player RVarane= new Player("Raphael", "Varane",CB, 14,84);
        Player KCas = new Player ("Kiko","Casilla",GK, 93,78);

        Player TStegen=new Player("Ter", "Stegen", GK, 1, 80);
        Player JAlba=new Player("Jordi", "Alba", LB,2, 83);
        Player GPique=new Player("Gerrard", "Pique", CB, 4, 84);
        Player JMascherano=new Player("Javier", "Mascherano", CB,5, 83);
        Player SRoberto=new Player("Sergi", "Roberto", RB, 3, 80);
        Player SBusquets=new Player("Sergio", "Busquets", CDM, 6, 86);
        Player IRakitic=new Player("Ivan", "Rakitic", CM, 8, 85);
        Player AIniesta=new Player("Andres", "Iniesta", CAM, 12, 88);
        Player LMessi=new Player("Lionel", "Messi", ST,10, 95);
        Player LSuarez=new Player("Luis", "Suarez", ST, 9, 92);
        Player Neymar=new Player("Neymar", "Jr", ST, 11, 93);

        Player SUmtiti= new Player("Samuel","Umtitti",CB,13,83);
        Player AGomes= new Player("Andre","Gomes",CM,14,79);
        Player PAlcacer = new Player("Paco","Alcacer",ST,15,82);

        Player CBravo=new Player("Claudio", "Bravo", GK, 1, 82);
        Player GClichy=new Player("Gael", "Clichy", LB, 22, 82);
        Player PZabaleta=new Player("Pablo", "Zabaleta", RB, 5, 85);
        Player JStones=new Player("John", "Stones", CB,11,81 );
        Player NOtamendi=new Player("Nicolas", "Otamendi", CB,30, 84);
        Player DSilva=new Player("David", "Silva", CAM,21, 88);
        Player Fernandinho=new Player("", "Fernandinho", CDM,22, 85);
        Player Fernando=new Player("Fernando", "", CDM, 6, 83);
        Player KDBruyne=new Player("Kevin", "De Bruyne", CAM, 17, 90);
        Player RSterling=new Player("Raheem", "Sterling", ST, 7, 87);
        Player SAguero=new Player("Sergio", "Aguero", ST, 9, 90);
        Player WCaballero= new Player("Willy","Caballero",GK,12,82);
        Player VKompany = new Player("Vincent","Kompany",CB,4,84);
        Player LSane = new Player("Leroy","Sane",RW,19,85);
        Player GJesus= new Player("Gabriel", "Jesus",ST,33,85);
        Player Nolito= new Player("Nolito","",LW,28,80);
        Player BSagna= new Player("Bacary","Sagna",RB,2,79);
        Player AKolarov= new Player("Aleksandar","Kolarov",LB,30,79);

        Player PCech=new Player("Petr", "Čech", GK, 33, 88);
        Player NMonreal=new Player("Nacho", "Monreal", LB, 18, 81);
        Player LKoscielny=new Player("Laurent", "Koscielny", CB, 6, 85);
        Player GPaulista=new Player("Gabriel", "Paulista", CB, 5, 84);
        Player HBellerín=new Player("Hector", "Bellerín	", RB, 24, 85);
        Player MÖzil=new Player("Mesut", "Özil", CAM, 11, 89);
        Player FCoquelin=new Player("Francis", "Coquelin", CDM, 34, 84);
        Player GXhaka=new Player("Granit", "Xhaka", CM, 29, 83);
        Player TWalcott=new Player("Theo", "Walcott", ST, 14, 86);
        Player ASánchez=new Player("Alexis", "Sánchez", ST, 7, 90);
        Player AIwobi=new Player("Alex", "Iwobi", CM, 17, 83);
        Player DOspina = new Player("David","Ospina",GK,12,82);
        Player ARamsey = new Player("Aaron","Ramsey",CM,8,83);
        Player OGiroud=  new Player("Oliver","Giroud",ST,9,84);
        Player Mustafi= new Player("","Mustafi",CB,15,83);
        Player AOChamberlain= new Player("Alex","Oxlade-Chamberlain",RW,20,82);
        Player LPerez= new Player("Lucas","Perez",ST,40,84);
        Player KGibbs=new Player("Keiran","Gibbs",RB,16,79);

        Player TCourtois=new Player("Thibout", "Courtois", GK, 13, 89);
        Player CAzpilicueta=new Player("Cesar", "Azpilicueta", CB, 28, 85);
        Player GCahill=new Player("Gary", "Cahill", CB,24, 83);
        Player DLuiz=new Player("David", "Luiz", CB, 30, 84);
        Player VMoses=new Player("Victor", "Moses", LB, 20, 83);
        Player MAlonso=new Player("Marcos", "Alonso", RB,3, 83);
        Player NKante=new Player("N'golo", "Kante", CDM, 7, 86);
        Player NMatic=new Player("Nemanja", "Matic", CDM, 6, 85);
        Player PRodriguez=new Player("Pedro", "Rodriguez", RW, 11, 86);
        Player EHazard=new Player("Eden", "Hazard", LW,10, 90);
        Player DCosta=new Player("Diego", "Costa", ST, 9, 88);


        Player MNeuer=new Player("Manuel", "Neuer", GK, 1, 89);
        Player DAlaba=new Player("David", "Alaba", LB, 2, 84);
        Player MHummels=new Player("Mats", "Hummels", CB, 3, 86);
        Player JBoateng=new Player("Jerome", "Boateng", CB, 17, 86);
        Player JKimmich=new Player("Joshua", "Kimmich", RB, 4, 83);
        Player XAlonso=new Player("Xabi", "Alonso", CDM, 5, 83);
        Player AVidal=new Player("Arturo", "Vidal", CM, 6, 86);
        Player TMuller=new Player("Thomas", "Muller", CAM, 10, 85);
        Player DGCosta=new Player("Douglas", "Costa", LW, 7, 84);
        Player ARobben=new Player("Arjen", "Robben", RW, 11, 85);
        Player RLewandowski=new Player("Robert", "Lewandowski", ST, 9, 90);

        Player PReina = new Player("Pepe","Reina",GK,12,79);
        Player FRibery = new Player("Franck","Ribery",LW,18,85);
        Player KComan= new Player("Kingsley","Coman",RW,19,83);
        Player JMartinez= new Player("Javi","Martinez",CDM,24,82);
        Player RSanches= new Player("Renato","Sanches",CM,20,82);


        Player Trapp=new Player("Trapp", "", GK, 1, 85);
        Player TSilva=new Player("Thiago", "Silva", CB, 2, 88);
        Player Marquinios=new Player("Marquinios", "", CB,5, 83);
        Player Meunier=new Player("Meunier", "Thoms", LB,12, 82);
        Player Kurzawa=new Player("Kurzawa", "", RB, 20, 83);
        Player BMatuidi=new Player("Blaise", "Matuidi", CDM,14, 86);
        Player GKrychowiak=new Player("Grzegorz", "Krychowiak", CDM, 8, 85);
        Player MVeratti=new Player("Marco", "Veratti", CAM, 6, 86);
        Player LMoura=new Player("Lucas", "Moura", RW, 7, 85);
        Player ECavani=new Player("Edinson", "Cavani", ST, 9, 88);
        Player CNkunku=new Player("Cristian", "Nkunku", CAM, 6, 86);
        Player DSubasic=new Player("Danjel","Subasic",GK,1,82);
        Player ARaggi=new Player("Andrea","Raggi ",CB,5,82);
        Player KGlik=new Player("Kamil","Glik",CB,4,86);
        Player Jemerson=new Player("Jemerson","",RB,2,81);
        Player YCissokho=new Player("Yarouba","Cissokho",LB,3,77);
        Player Bakayoko=new Player("","Bakayoko",CDM,10,85);
        Player JMoutinho=new Player("Joao","Moutinho",CM,8,84);
        Player TLemar=new Player("Thomas","Lemar",CM,6,83);
        Player BSilva=new Player("Bernardo","Silva",CAM,7,84);
        Player KMbappe=new Player("Kyllian","Mbappe",ST,11,86);
        Player RFalcao=new Player("Radamel","Falcao",ST,9,86);
        Player HLloris=new Player("Hugo","Lloris",GK,1,88);
        Player TAlderweireld=new Player("Toby","Alderweireld",CB,4,85);
        Player JVertonghen=new Player("Jan","Vertonghen",CB,5,83);
        Player KWalker=new Player("Kyle","Walker",RB,3,81);
        Player DRose=new Player("Danny","Rose",LB,2,83);
        Player MDembele=new Player("Moussa","Dembele",CM,7,85);
        Player VWanyama=new Player("Victor","Wanyama",CM,8,86);
        Player DAlli=new Player("Delle","Alli",CAM,11,84);
        Player SHueng=new Player("Son","Hueng",ST,10,83);
        Player HKane=new Player("Harry","Kane",ST,9,85);
        Player CEriksen=new Player("Cristian","Eriksen",CAM,10,84);
        Player Burki=new Player("Burki","",GK,1,81);
        Player SPapasdopulos=new Player("Sokratis","Papasdopulos",CB,4,84);
        Player LPiszczek=new Player("Lukasz","Piszczek",RB,3,82);
        Player MBartra=new Player("Marc","Bartra",CB,5,81);
        Player CPulisic=new Player("Christian","Pulisic",LB,2,80);
        Player SKagawa=new Player("Shinji","Kagawa",CM,8,83);
        Player MGoetze=new Player("Mario","Goetze",CAM,7,84);
        Player ASchurrle=new Player("Andre","Schurrle",CAM,8,81);
        Player ODembele=new Player("Osama","Dembele",RW,10,81);
        Player Reus=new Player("Marco","Reus",LW,11,88);
        Player PAubameyang=new Player("Pierre-Emerick","Aubameyang",ST,9,87);
        Player JOblak=new Player("Jan","Oblak",GK,1,87);
        Player DGodin=new Player("Diego","Godin",CB,3,88);
        Player FLuis=new Player("Felipe","Luis",LB,4,85);
        Player Savic=new Player("Savic","",CB,5,83);
        Player Juanfran=new Player("Juanfran","",RB,2,83);
        Player MGaitan=new Player("Marcos","Gaitan",CM,7,85);
        Player YCarrasco=new Player("Yannick","Carrasco",CM,8,82);
        Player Gabi=new Player("Gabi","",CM,6,82);
        Player Koke=new Player("Koke","",CM,10,84);
        Player AGriezmann=new Player("Antoine","Griezmann",ST,11,88);
        Player FTorres=new Player("Fernando","Torres",ST,9,81);
        Player TShinhan=new Player("Tien","Shinhan ",GK,1,82);
        Player Yamcha=new Player("Yamcha"," ",CB,5,81);
        Player Krillin=new Player("Krillin"," ",CB,4,82);
        Player Roshi=new Player("Master","Roshi ",LB,3,81);
        Player Whis=new Player("Whis"," ",RB,2,99);
        Player Piccolo=new Player("Piccolo"," ",CM,6,84);
        Player Trunks=new Player("Trunks"," ",CAM,7,83);
        Player Goten=new Player("Goten"," ",CDM,8,83);
        Player Vegeta=new Player("Vegeta"," ",LW,9,95);
        Player Goku=new Player("Goku"," ",ST,10,94);
        Player Beerus=new Player("Beerus"," ",RW,11,97);
        Player Jamemba=new Player("Jamemba"," ",GK,1,89);
        Player Turles=new Player("Turles"," ",CB,2,70);
        Player Brolly=new Player("Brolly"," ",CB,3,93);
        Player Nappa=new Player("Nappa"," ",CB,4,75);
        Player Cell=new Player("Cell"," ",RB,5,89);
        Player Buu=new Player("Buu"," ",LB,6,93);
        Player Frieza=new Player("Frieza"," ",CM,7,87);
        Player Android=new Player("Android","17 ",CM,17,87);
        Player Black=new Player("Black","",CAM,9,94);
        Player Zamasu=new Player("Zamasu"," ",CAM,11,89);
        Player Ginyu=new Player("Ginyu"," ",ST,10,80);
        //Superstarr
        Player HBajda=new Player("Henryk","Bajda",GK,1,84);
        Player SJach=new Player("Stanisław 'Stajku'","Jach",CB,2,90);
        Player APastuszek=new Player("Adam 'Chomik'","Pastuszek",CB,4,90);
        Player HMinus=new Player("Herkules","Minus",CB,3,83);
        Player BBolek=new Player("Bolek","",LB,5,83);
        Player FGerula=new Player("Florian","Gerula",RB,6,86);
        Player MGerula=new Player("Marian","Gerula",CM,7,86);
        Player CGerula=new Player("Czesław","Gerula",CM,8,86);
        Player JSzpytman=new Player("Jarosław 'Pitas'","Szpytman",CM,23,89);
        Player KWojtowicz=new Player("Kamil 'Kombajn'","Wojtowicz",ST,10,87);
        Player ŁJach=new Player("Łukasz Kryminał","Jach",ST,9,87);
        // Huragan
        Player MDaraz=new Player("Maciej", "Daraz", GK, 12, 87);
        Player MZatawrdnicki=new Player("Maciej", "Zatawrdnicki", CB, 2, 83);
        Player BZatwardnicki=new Player("Bartosz", "Zatwardnicki", CB, 4, 90);
        Player DMazur=new Player("Damian", "Mazur", LB, 3, 89);
        Player KLewiarz=new Player("Krzysztof", "Lewiarz", RB, 11, 88);
        Player DFudali=new Player("Daniel", "Fudali", CDM,6, 90);
        Player BFrosztega=new Player("Bartosz", "Frosztega", CM,13, 83);
        Player LPawlowski=new Player("Łukasz", "Pawłowski", RW, 19, 90);
        Player DPawlowski=new Player("Daniel", "Pawłowski", CAM, 10, 90);
        Player BDzimira=new Player("Bogumił", "Dzimira", ST,9, 91);
        Player APawlowski=new Player("Arkadiusz", "Pawłowski", LW, 7, 94);
        // Legends
        Player GBednarczyk=new Player("Grzegorz","Bednarczyk",GK,12,87);
        Player MGłuszko=new Player("Mieczysław","Głuszko",LB,3,86);
        Player MPawłowski=new Player("Marian","Pawłowski",CB,2,85);
        Player PDzidek=new Player("Paweł","Dzidek",CB,3,87);
        Player ZPawłowski=new Player("Zenon","Pawłowski",RB,5,84);
        Player EFudali=new Player("Edward","Fudali",CDM,7,84);
        Player DSzpytman=new Player("Dawid","Szpytman",CDM,8,85);
        Player STomaszewski=new Player("Szymon ","Tomaszewski",CAM,10,94);
        Player LChorbowy=new Player("Leon","Chorbowy",CAM,4,88);
        Player MSzpytman=new Player("Marek","Szpytman",CAM,88,85);
        Player WBajda=new Player("Wiesław","Bajda",ST,11,87);
        Player LDaraż=new Player("Łukasz","Daraż",CB,70,86);
        Player DGłowacz=new Player("Dawid","Głowacz",RM,8,85);
        Player AWanat= new Player("Arkadiusz","Wanat",CM,96,84);
        Player MPawlowski= new Player("Marcin","Pawłowski",LB,25,87);
        Player MBus= new Player("Mateusz","Buś",CB,74,85);
        Player JKwasny=new Player("Józef","Kwaśny",GK,1,87);
        Player KPastuszek= new Player("Kacper","Pastuszek",ST,69,84);
        Player BBajda=new Player("Bartosz","Bajda",CB,22,79);
        Player JGerula=new Player("Jacek","Gerula",ST,9,86);
        Player PGerula=new Player("Piotr","Gerula",ST,19,88);
        Player JBajda=new Player("Jarosław","Bajda",CB,26,84);
        Player DBochenek= new Player("Damian","Bochenek",CB,14,89);
        Player PMikita= new Player("Piotr","Mikita",CDM,30,79);
        Player EKowalinski= new Player("Eugeniusz","Kowaliński",RB,32,80);
        Player JGluszko=new Player("Jarosław","Głuszko",CM,18,87);
        Player KZabawski= new Player("Krystian","Zabawski",CM,42,87);
        Player DZabawski= new Player("Damian","Zabawski",CB,41,80);
        Player SFednar= new Player("Sylwester","Fednar",RM,21,80);
        Player MFednar= new Player("Marcin","Fednar",CM,17,82);
        Player DSwist= new Player("Dominik","Swist",RW,27,85);
        Player MSwist= new Player("Mateusz","Swist",LW,28,86);
        Player ABegovic = new Player("Asmir","Begovic",GK,1,81);
        Player KZouma = new Player("Kurt","Zouma",CB,4,80);
        Player CFabregas = new Player("Cesc","Fabregas",CM,4,83);
        Player Willian = new Player("Willian","",RW,22,85);
        Player NAke = new Player("Nathan","Ake",RB,12,77);
        Player MBatshuai = new Player("Michy","Batshuai",ST,19,81);
        Player RLCheek = new Player("Ruben","Loftus-Cheek",CM,20,79);


        // stworzenie tablicy zespołów i przypisanie do niej zespołów (pozycja [16] jest pozycją buforową aby w późniejszym etapie możliwe były zmiany pozycji zespołów w tablicy)
        teams = new Team[16];
        teams[0]=new Team("Real Madrid","Spain", formations.get(0),KNavas,	Marcelo,SRamos,Pepe,DCarvajal,TKroos,LModric,JRodriguez,CRonaldo,GBale,AMorata);
        teams[1]=new Team( "FC Barcelona", "Spain",formations.get(0), TStegen,JAlba,GPique,JMascherano,SRoberto,SBusquets,IRakitic,AIniesta,LMessi,LSuarez,Neymar);
        teams[2]=new Team( "Huragan Reczpol", "Poland",formations.get(2),  MDaraz,MZatawrdnicki,	BZatwardnicki,DMazur,KLewiarz,DFudali,BFrosztega,LPawlowski,DPawlowski,BDzimira,APawlowski);
        teams[3]=new Team( "Manchester City", "England",formations.get(0),  CBravo,	GClichy,PZabaleta,JStones,NOtamendi,DSilva,Fernandinho,Fernando,KDBruyne,RSterling,SAguero);
        teams[4]=new Team( "Arsenal FC", "England",formations.get(0),  PCech,NMonreal,LKoscielny,GPaulista,	HBellerín,FCoquelin,GXhaka,TWalcott,ASánchez,AIwobi,MÖzil);
        teams[5]=new Team( "Chelsea FC", "England",formations.get(0),  TCourtois,CAzpilicueta,GCahill,DLuiz,VMoses,MAlonso,NKante,NMatic,PRodriguez,EHazard,DCosta);
        teams[6]=new Team("Bayern Munich", "Germany",formations.get(0), MNeuer,	DAlaba,	MHummels,JBoateng,JKimmich,XAlonso,	AVidal,TMuller,DGCosta,ARobben,RLewandowski);
        teams[7]=new Team("PSG","France",formations.get(0), Trapp,	TSilva,	Marquinios,Meunier,Kurzawa,BMatuidi,GKrychowiak,MVeratti,LMoura,	ECavani,CNkunku);
        teams[8]=new Team("AS Monaco","France",formations.get(0),DSubasic,ARaggi,KGlik,Jemerson,YCissokho,Bakayoko,JMoutinho,TLemar,BSilva,	KMbappe,RFalcao);
        teams[9]=new Team("Tottenham Hotspur","England",formations.get(0), HLloris,TAlderweireld,JVertonghen,KWalker,DRose,MDembele,VWanyama,DAlli,SHueng,	HKane,CEriksen);
        teams[10]=new Team("Borussia Dortmund","Germany",formations.get(0), Burki,SPapasdopulos,LPiszczek,	MBartra,CPulisic,SKagawa,MGoetze,ASchurrle,ODembele,Reus,PAubameyang);
        teams[11]=new Team("Atletico Madrid", "Spain",formations.get(0), JOblak,	DGodin,	FLuis,Savic,Juanfran,	MGaitan,YCarrasco,Gabi,Koke,AGriezmann,FTorres) ;
        teams[12]=new Team("DragunboluGut","Japan",formations.get(0), TShinhan,Yamcha,Krillin,Roshi,Whis,Piccolo,Trunks,Goten,Vegeta,Goku,Beerus);
        teams[13]=new Team("DragunboluBat","Japan",formations.get(0),Jamemba,Turles,Brolly,Nappa,Cell,Buu,Frieza,Android,Black,Zamasu,Ginyu);
        teams[14]=new Team("Reczpol Superstar","Poland",formations.get(0), HBajda,SJach,APastuszek,HMinus,BBolek,FGerula,MGerula,CGerula,JSzpytman,KWojtowicz,ŁJach);
        teams[15]=new Team("Reczpol Legends","Poland",formations.get(0),GBednarczyk,MGłuszko,MPawłowski,PDzidek,ZPawłowski,	EFudali,DSzpytman,STomaszewski,LChorbowy,MSzpytman,WBajda);

        teams[0].addPlayer(KCas);
        teams[0].addPlayer(Isco);
        teams[0].addPlayer(Casemiro);
        teams[0].addPlayer(KBenzema);
        teams[0].addPlayer(MAsensio);
        teams[0].addPlayer(RVarane);
        teams[0].addPlayer(LVasquez);

        teams[3].addPlayer(WCaballero);
        teams[3].addPlayer(BSagna);
        teams[3].addPlayer(AKolarov);
        teams[3].addPlayer(LSane);
        teams[3].addPlayer(Nolito);
        teams[3].addPlayer(VKompany);
        teams[3].addPlayer(GJesus);

        teams[4].addPlayer(DOspina);
        teams[4].addPlayer(KGibbs);
        teams[4].addPlayer(AOChamberlain);
        teams[4].addPlayer(LPerez);
        teams[4].addPlayer(OGiroud);
        teams[4].addPlayer(Mustafi);
        teams[4].addPlayer(ARamsey);


        teams[5].addPlayer(ABegovic);
        teams[5].addPlayer(Willian);
        teams[5].addPlayer(NAke);
        teams[5].addPlayer(RLCheek);
        teams[5].addPlayer(CFabregas);
        teams[5].addPlayer(KZouma);
        teams[5].addPlayer(MBatshuai);

        teams[2].addPlayer(LDaraż);
        teams[2].addPlayer(DGłowacz);
        teams[2].addPlayer(AWanat);
        teams[2].addPlayer(MPawlowski);
        teams[2].addPlayer(MBus);
        teams[2].addPlayer(JKwasny);
        teams[2].addPlayer(KPastuszek);

        teams[14].addPlayer(BBajda);
        teams[14].addPlayer(JGerula);
        teams[14].addPlayer(PGerula);
        teams[14].addPlayer(JBajda);
        teams[14].addPlayer(DBochenek);
        teams[14].addPlayer(PMikita);
        teams[14].addPlayer(EKowalinski);

        teams[15].addPlayer(JGluszko);
        teams[15].addPlayer(KZabawski);
        teams[15].addPlayer(DZabawski);
        teams[15].addPlayer(SFednar);
        teams[15].addPlayer(MFednar);
        teams[15].addPlayer(DSwist);
        teams[15].addPlayer(MSwist);

        for(int i=0; i<teams.length; i++) teams[i].bestSetUp(formations,false);
    }
   
    private void button_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_startActionPerformed
        new GameStartMenu().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_button_startActionPerformed

    private void button_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_connectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_connectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_connect;
    private javax.swing.JButton button_start;
    private javax.swing.JTextField field_ip;
    private javax.swing.JLabel field_no_connection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
